### ISSUE TITLE
Slow Documentation diff (and failure with timeouts)

### ISSUE THREAD

**Issue by aschillio** [bump-sh/github-action#379]
From time to time, the ci is failing on diff our API. (Not always). The error is not really explicit could you help ?
Do you have options to debug ?
Thanks.

The job:
```
on: pull_request
jobs:
  api-diff:
    name: Check API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Cache dependencies...
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/back/node_modules
            packages/shared/node_modules
            packages/web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages...
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn --prefer-offline --frozen-lockfile --ignore-scripts --silent
      - name: Generate swagger
        run: yarn api api:generate-swagger:internal
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: cmp
          token: ${{secrets.BUMP_TOKEN}}
          file: ./packages/back/dist/src/presentation/rest-api/v1/internal/swagger.json
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

<img width="910" alt="Screenshot 2023-03-10 at 10 38 53" src="https://user-images.githubusercontent.com/89770830/224281017-7a708a0e-d6de-4552-952c-bf0aa7ee9fa0.png">
