### ISSUE TITLE
[BUG] Can't see diff from slack bot

### ISSUE THREAD

**Issue by aschillio** [bump-sh/github-action#388]
We have an issue with the slack extension posting diff. The link seems dead.

```
jobs:
  deploy_open_api_doc:
    name: Deploy Open API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Cache dependencies...
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/back/node_modules
            packages/shared/node_modules
            packages/web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages...
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn --prefer-offline --frozen-lockfile --ignore-scripts --silent
      - name: Generate swagger
        run: yarn api api:generate-swagger:internal
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: 77be3950-fd14-481e-9fa1-57cfaeb73d02
          token: ${{secrets.BUMP_TOKEN}}
          file: ./packages/back/dist/src/presentation/rest-api/v1/internal/swagger.json
```

I see in your actions example you are using checkout@v2 and not v3, could it impact the diff link ? Thanks a lot.

<img width="1689" alt="Screenshot 2023-03-23 at 10 12 59" src="https://user-images.githubusercontent.com/89770830/227157229-45700259-c939-4587-8706-fa52123f9d85.png">
